# Generated by Django 3.1 on 2020-08-20 03:00

import clock.tasks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('task', models.CharField(choices=[('helloworld', clock.tasks.helloworld)], max_length=20)),
            ],
        ),
    ]
