# Generated by Django 3.1 on 2020-08-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0002_auto_20200820_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='task',
            field=models.CharField(choices=[('helloworld', 'helloworld')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
