# Generated by Django 3.1 on 2020-08-21 02:32

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0003_interval_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='*', help_text='4-digit year', max_length=4)),
                ('month', models.CharField(default='*', help_text='month (1-12)', max_length=2)),
                ('day', models.CharField(default='*', help_text='day of the (1-31)', max_length=2)),
                ('week', models.CharField(default='*', help_text='ISO week (1-53)', max_length=2)),
                ('day_of_week', models.CharField(default='*', help_text='number or name of weekday (0-6 or mon,tue,wed,thu,fri,sat,sun)', max_length=40)),
                ('hour', models.CharField(default='*', help_text='hour (0-23)', max_length=2)),
                ('minute', models.CharField(default='*', help_text='minute (0-59)', max_length=2)),
                ('second', models.CharField(default='*', help_text='second (0-59)', max_length=2)),
                ('start_date', models.DateTimeField(blank=True, help_text='earliest possible date/time to trigger on (inclusive)', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='latest possible date/time to trigger on (inclusive)', null=True)),
                ('jitter', models.SmallIntegerField(default=10, help_text='advance or delay the job execution by ``jitter`` seconds at most')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('changed_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '循环执行任务',
                'verbose_name_plural': '循环执行任务',
            },
        ),
        migrations.AlterModelOptions(
            name='date',
            options={'verbose_name': '一次性执行计划', 'verbose_name_plural': '一次性执行计划'},
        ),
        migrations.AlterModelOptions(
            name='interval',
            options={'verbose_name': '间隔执行任务', 'verbose_name_plural': '间隔执行任务'},
        ),
        migrations.AddField(
            model_name='date',
            name='changed_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='date',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interval',
            name='changed_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interval',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 21, 2, 32, 30, 731194, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interval',
            name='jitter',
            field=models.SmallIntegerField(default=10, help_text='advance or delay the job execution by ``jitter`` seconds at most'),
        ),
    ]
