# Generated by Django 3.1 on 2020-08-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0005_cron_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cron',
            name='day',
            field=models.CharField(default='*', help_text='day of the (1-31)', max_length=20),
        ),
        migrations.AlterField(
            model_name='cron',
            name='hour',
            field=models.CharField(default='*', help_text='hour (0-23)', max_length=20),
        ),
        migrations.AlterField(
            model_name='cron',
            name='minute',
            field=models.CharField(default='*', help_text='minute (0-59)', max_length=20),
        ),
        migrations.AlterField(
            model_name='cron',
            name='month',
            field=models.CharField(default='*', help_text='month (1-12)', max_length=20),
        ),
        migrations.AlterField(
            model_name='cron',
            name='second',
            field=models.CharField(default='*', help_text='second (0-59)', max_length=20),
        ),
        migrations.AlterField(
            model_name='cron',
            name='week',
            field=models.CharField(default='*', help_text='ISO week (1-53)', max_length=20),
        ),
        migrations.AlterField(
            model_name='cron',
            name='year',
            field=models.CharField(default='*', help_text='4-digit year', max_length=20),
        ),
    ]
