# Generated by Django 3.1 on 2020-08-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0006_auto_20200821_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cron',
            options={'verbose_name': 'cron', 'verbose_name_plural': 'cron'},
        ),
        migrations.AlterModelOptions(
            name='date',
            options={'verbose_name': 'date', 'verbose_name_plural': 'date'},
        ),
        migrations.AlterModelOptions(
            name='interval',
            options={'verbose_name': 'interval', 'verbose_name_plural': 'interval'},
        ),
        migrations.RenameField(
            model_name='cron',
            old_name='task',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='date',
            old_name='task',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='interval',
            old_name='task',
            new_name='event',
        ),
        migrations.AddField(
            model_name='cron',
            name='name',
            field=models.CharField(default='', help_text='What Event!', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='date',
            name='name',
            field=models.CharField(default='', help_text='What Event!', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interval',
            name='name',
            field=models.CharField(default='', help_text='What Event!', max_length=200),
            preserve_default=False,
        ),
    ]
